spring.application.name=Backend
spring.datasource.url=${DATABASE_URL}
server.port=${PORT:8080}

wallet.api.url=${WALLET_URL}
wallet.api.key=${WALLET_API_KEY}

spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000

spring.datasource.hikari.minimum-idle=2