spring.application.name=Backend
spring.datasource.url=jdbc:postgresql://ep-still-lake-aoou7d9i-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_6wyO9XNuFLMC&sslmode=require&channelBinding=require

wallet.api.url=https://jigsaw-coin-api.vercel.app
wallet.api.key=46f7b70c83e8cbe148d7b304b9cce0dc9db0079e0e8939995ac2dce8f118ee5c

spring.jpa.hibernate.ddl-auto=update